install:
	mkdir -p '$(HOME)/Library/Application Support/Code/User'
	stow -v --ignore Makefile -t $(HOME) .
	code --install-extension akamud.vscode-theme-onedark
	code --install-extension file-icons.file-icons
	code --install-extension golang.Go
	code --install-extension ziyasal.vscode-open-in-github
	code --install-extension ms-python.python
	code --install-extension ms-python.vscode-pylance
	code --install-extension hashicorp.terraform
	code --install-extension eamodio.gitlens
