install:
	mkdir -p '$(HOME)/Library/Application Support/Code/User'
	stow -v --ignore Makefile -t $(HOME) .
	brew cask install visual-studio-code
	code --install-extension akamud.vscode-theme-onedark
	code --install-extension peterjausovec.vscode-docker
	code --install-extension file-icons.file-icons
	code --install-extension ms-vscode.go
	code --install-extension ziyasal.vscode-open-in-github
	code --install-extension ms-python.python
