work = system("dsconfigad -show | grep --quiet babylonhealth")
home = !work

brew 'asciinema'
brew 'ansible'
brew 'apgdiff'
brew 'awscli'
brew 'bash-completion'
brew 'bat'
brew 'bazel'
brew 'colordiff'
brew 'coreutils'
brew 'cowsay'
brew 'cloc'
brew 'ctags'
brew 'ctop'
brew 'curl'
brew 'dep'
brew 'diff-so-fancy'
brew 'direnv'
brew 'fd'
brew 'ffmpeg'
brew 'fish'
brew 'flake8'
brew 'fzf'
brew 'git'
brew 'gnuplot'
brew 'go'
brew 'go-jira'
brew 'httpie'
brew 'hub'
brew 'hugo'
brew 'imagemagick'
brew 'jq'
brew 'keychain'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'lcov'
brew 'ledger' if home
brew 'nmap'
brew 'node'
brew 'optipng'
brew 'readline'
brew 'rsync'
brew 'pgcli'
brew 'pipenv'
brew 'postgresql'
brew 'pre-commit'
brew 'pwgen'
brew 'pyenv'
brew 'python2'
brew 'python3'
brew 'rustup-init'
brew 'sbt'
brew 'shellcheck'
brew 'sqlite'
brew 'ssh-audit'
brew 'stow'
brew 'telnet'
brew 'terraform'
brew 'tig'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'vault'
brew 'vim'
brew 'watch'
brew 'webpack'
brew 'wget'
brew 'yarn'
brew 'youtube-dl' if home

tap 'burntsushi/ripgrep', 'https://github.com/BurntSushi/ripgrep.git'
brew 'burntsushi/ripgrep/ripgrep-bin'

tap 'homebrew/cask-drivers'
cask '1password'
cask 'anybar'
cask 'arq' if home
cask 'atom'
cask 'dash'
cask 'deluge' if home
cask 'docker'
cask 'etcher'
cask 'garmin-express' if home
cask 'google-chrome'
cask 'google-hangouts'
cask 'gpxsee' if home
cask 'insomnia'
cask 'keybase'
cask 'musicbrainz-picard' if home
cask 'skype' if work
cask 'slack' if work
cask 'sonos' if home
cask 'spectacle'
cask 'spotify'
cask 'sublime-merge'
cask 'sublime-text'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'wacom-tablet'
cask 'whatsapp' if home
cask 'zoomus' if work
cask 'zwift' if home

tap 'caskroom/versions'
cask 'java8'

tap 'homebrew/cask-fonts'
cask 'font-fira-code'
cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'

tap 'rupert/repo'
brew 'google-photos-backup'

tap 'rupert/private'
cask 'mischief-free'

mas 'Encrypto', id: 935235287 if work
mas 'Things3', id: 904280696

tap 'babylonpartners/babylon'
# env HOMEBREW_GITHUB_API_TOKEN=<snip> brew install shipcat
