work = system("dsconfigad -show | grep --quiet babylonhealth")
home = !work

brew 'ansible'
brew 'apgdiff'
brew 'awscli'
brew 'bash-completion'
brew 'bat'
brew 'colordiff'
brew 'coreutils'
brew 'cloc'
brew 'ctags'
brew 'curl'
brew 'diff-so-fancy'
brew 'direnv'
brew 'fd'
brew 'ffmpeg'
brew 'fish'
brew 'fzf'
brew 'git'
brew 'go'
brew 'go-jira'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'kubernetes-cli'
brew 'ledger' if home
brew 'node'
brew 'readline'
brew 'pipenv'
brew 'postgresql'
brew 'pwgen'
brew 'pyenv'
brew 'python2'
brew 'python3'
brew 'shellcheck'
brew 'sqlite'
brew 'stow'
brew 'telnet'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'youtube-dl' if home

tap 'burntsushi/ripgrep', 'https://github.com/BurntSushi/ripgrep.git'
brew 'burntsushi/ripgrep/ripgrep-bin'

tap 'homebrew/cask-drivers'
cask '1password'
cask 'anybar'
cask 'arq' if home
cask 'atom'
cask 'dash'
cask 'deluge' if home
cask 'docker'
cask 'garmin-express' if home
cask 'google-chrome'
cask 'google-hangouts'
cask 'gpxsee' if home
cask 'insomnia'
cask 'musicbrainz-picard' if home
cask 'skype' if work
cask 'sonos' if home
cask 'spectacle'
cask 'spotify'
cask 'sublime-merge'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp' if home
cask 'zoomus' if work
cask 'zwift' if home

tap 'caskroom/versions'
cask 'java8'

tap 'homebrew/cask-fonts'
cask 'font-fira-code'
cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'

mas 'Encrypto', id: 935235287 if work
mas 'Things3', id: 904280696
